services:
  web:
    build: .
    labels:
      - "lazytainer.group=web"
    depends_on:
      - redis
      - lazytainer
  
  lazytainer:
    image: ghcr.io/vmorganp/lazytainer:master
    ports:
      - 5000:5000
      - 6379:6379
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      - "lazytainer.group.database.ports=6379"

  redis:
    image: redis:alpine
    volumes:
      - ./redis:/data
    labels:
      - "lazytainer.group=database"
    depends_on:
      - lazytainer